[supervisord]
nodaemon=true

[program:queue-worker]
command=php artisan queue:work --tries=3 --backoff=5 --sleep=3 --timeout=30 --max-time=3600
autostart=true
autorestart=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0